version: "3.3"
services:
  webapplication2:
    image: webapplication2
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000